subsystems:
    drivetrain:
        implemented: true
        talons:
            leftMain: 2
            leftSlaveOne: -1
            leftSlaveTwo: -1
            rightMain: 1
            rightSlaveOne: -1
            rightSlaveTwo: -1
        constants:
            doubles:
                pigeonId: 13
                pigeonOnTalon: 0
                kP: 0
                kI: 0
                kD: 0
                kF: 1.70
                iZone: 28.884639745885927
                encPPR: 960
                invertMotor: 2
    canifier:
        implemented: true
        constants:
            doubles:
                canId: 12
constants:
    doubles:
        wheelDiameter: 3.92820959548
        trackWidth: 15.75
        maxVel: 25
        maxAccel: 75
        sensorPhase: 0
        kLooperDt: .01
        kTrackScrubFactor: 1.0
        kPCMId: 0
        pathKs: 0
    booleans:
        verbose: true
