subsystems:
  drivetrain:
    implemented: true
    talons:
      leftMain: 1
      leftSlaveOne: 2
      rightMain: 14
      rightSlaveOne: 13
    invertMotor:
        - 14
    victors:
      rightSlaveTwo: 15
      leftSlaveTwo: 0
    constants:
      pigeonId: 3
      pigeonOnTalon: 1
      kP: 1.8
      kI: .05
      kD: 18
      kF: 0.91
      iZone: 0
      encPPR: 1015.3333333333
      currentFloorCheck: .4
      currentEpsilonCheck: .2
      rpmFloorCheck: 500
      rpmEpsilonCheck: 60
  canifier:
    implemented: true
    constants:
      canId: 18
constants:
  wheelDiameter: 5.72332
  trackWidth: 25
  maxVel: 40 #inch/s
  maxAccel: 30 #inch/s^2
  sensorPhase: 0
  kLooperDt: .030
  kTrackScrubFactor: 1.0
  kPCMId: 0
  pathKs: 2
  verbose: 0
