!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers:
- mHandle: 439
  mName: Pigeon X
  mType: com.snobot.simulator.simulator_components.ctre.CtrePigeonImuSim$PigeonAccelWrapper
- mHandle: 440
  mName: Pigeon Y
  mType: com.snobot.simulator.simulator_components.ctre.CtrePigeonImuSim$PigeonAccelWrapper
- mHandle: 441
  mName: Pigeon Z
  mType: com.snobot.simulator.simulator_components.ctre.CtrePigeonImuSim$PigeonAccelWrapper
mAnalogIn: []
mAnalogOut: []
mDefaultI2CWrappers: {}
mDefaultSpiWrappers: {}
mDigitalIO:
- mHandle: 4
  mName: Digital IO 4
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
mEncoders:
- mConnectedSpeedControllerHandle: 101
  mHandle: 101
  mName: CAN Encoder (1)
  mType: com.snobot.simulator.simulator_components.smart_sc.SmartScEncoder
- mConnectedSpeedControllerHandle: 102
  mHandle: 102
  mName: CAN Encoder (2)
  mType: com.snobot.simulator.simulator_components.smart_sc.SmartScEncoder
mGyros:
- mHandle: 439
  mName: Pigeon Yaw
  mType: com.snobot.simulator.simulator_components.ctre.CtrePigeonImuSim$PigeonGyroWrapper
- mHandle: 440
  mName: Pigeon Pitch
  mType: com.snobot.simulator.simulator_components.ctre.CtrePigeonImuSim$PigeonGyroWrapper
- mHandle: 441
  mName: Pigeon Roll
  mType: com.snobot.simulator.simulator_components.ctre.CtrePigeonImuSim$PigeonGyroWrapper
mPwm:
- mHandle: 100
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: CTRE SC 0
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 101
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: CTRE SC 1
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 102
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: CTRE SC 2
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
mRelays: []
mSimulatorComponents:
- !!com.snobot.simulator.simulator_components.config.TankDriveConfig
  mGyroHandle: 439
  mLeftMotorHandle: 100
  mRightMotorHandle: 101
  mTurnKp: 1.0
mSolenoids: []
